### ISSUE TITLE
Butterknife not generate the class correctly on different machine

### ISSUE THREAD

**Issue by ricoharisin91** [JakeWharton/butterknife#856] opened 2017-01-24 12:00 UTC
i have a problem that make me headache this week

my project is multi module and contain 6 library and 2 application

i have a core library, let's call it ``core_lib`` which implement butterknife because there is some layout in there

and i have another library which depends on ``core_lib`` let's call it ``sub_lib`` this library also implement butterknife

so the schema will be like this

core_lib
|
sub_lib
|
app

the problem is, i try to build it, working fine on my own machine with debug, release even signed it. But when i tried on different machine, which is my build machine, the generated class on ``sub_lib`` not refer to right id, instead it's refer to another id on ``core_lib``

generated class on my own machine, the correct one

	  @UiThread
	  public TopAdsDashboardActivity_ViewBinding(T target, View source) {
	    this.target = target;

	    target.viewPager = Utils.findRequiredViewAsType(source, R.id.pager, "field 'viewPager'", ViewPager.class);
	    target.indicator = Utils.findRequiredViewAsType(source, R.id.indicator, "field 'indicator'", TabLayout.class);
	  }

generated class on my build machine

	@UiThread
	  public TopAdsDashboardActivity_ViewBinding(T target, View source) {
	    this.target = target;

	    target.viewPager = Utils.findRequiredViewAsType(source, R.id.add_button, "field 'viewPager'", ViewPager.class);
	    target.indicator = Utils.findRequiredViewAsType(source, R.id.info_shop, "field 'indicator'", TabLayout.class);
	  }

i already tried with the same command to build and make sure the gradle version is same, but the problem still there, generated class on ``sub_lib`` not generated correctly ONLY on my build machine. working very fine on my own machine

i'm using butterknife 8.4.0

any clue or solution will be appreciated 

thanks!

**Comment by JakeWharton** [comment] 2017-01-24 16:57
Dupe of #779.

**Closed by JakeWharton** 2017-01-24 16:57 UTC
