### ISSUE TITLE
Bind service

### ISSUE THREAD

**Issue by dbarwacz** [JakeWharton/butterknife#711] opened 2016-08-19 12:11 UTC
Theoretically there is no point binding views to service but when developer wants to perform some calculations on dimens when drawing over system window, then binding would be useful. Please consider adding method ButterKnife.bind(Service) to enable such functionality.

**Comment by JakeWharton** [comment] 2016-08-19 14:39
Dupe of #282.

**Closed by JakeWharton** 2016-08-19 14:39 UTC
