### ISSUE TITLE
@BindArray is missing

### ISSUE THREAD

**Issue by Macarse** [JakeWharton/butterknife#308] opened 2015-07-10 00:57 UTC
Example:
```
@BindArray(R.array.my_array) String[] array;
```

In `arrays.xml`:

```
  <string-array name="my_array">
    <item>@string/element_1</item>
    <item>@string/element_2</item>
  </string-array>
```

**Comment by JakeWharton** [comment] 2015-07-10 01:02
Dupe of #294, #297.

**Closed by JakeWharton** 2015-07-10 01:02 UTC
