### ISSUE TITLE
generated ViewBinding doesn't extend superclass ViewBinding when in separate modules

### ISSUE THREAD

**Issue by kassim** [JakeWharton/butterknife#1180] opened 2018-01-10 11:38 UTC
I have a `ui` module with a BaseFragment class with a binding to a view
I then have my main `app` module with a WebViewFragment with other view bindings

I can see that WebViewFragment_ViewBinding doesn't extend BaseFragment_ViewBinding, and thus my views in the BaseFragment are never injected.

A temporary workaround is to call `new BaseFragment_ViewBinding()` by itself, but I don't think this is how its supposed to work, is it?

**Comment by JakeWharton** [comment] 2018-01-10 14:32
Dupe of #808

**Closed by JakeWharton** 2018-01-10 14:32 UTC
