### ISSUE TITLE
Butterknife doesnt work when the Activity is inside a packge

### ISSUE THREAD

**Issue by Edmes** [JakeWharton/butterknife#609] opened 2016-06-07 05:36 UTC
When i have my Activity inside a project structure like following:
  Login(package) -> Activity (Package) -> LoginActivity.java
I got an error saying that can't find the class Login and the package Login.Activity does not exist, but when i have mi LoginActivity.java in the root directory it works 

```ruby
C:\Users\Edgar\Documents\GeoPromociones\app\build\generated\source\apt\debug\com\karina\app\geopromociones\Login\Activity\LoginActivity$$ViewBinder.java
Error:(9, 37) error: cannot find symbol class Login
Error:(14, 64) error: package Login.Activity does not exist
Error:(48, 64) error: package Login.Activity does not exist
Error:(9, 37) error: cannot find symbol class Login
Error:(14, 64) error: package Login.Activity does not exist
Error:(48, 64) error: package Login.Activity does not exist
```

```ruby
// Generated code from Butter Knife. Do not modify!
package com.karina.app.geopromociones.Login.Activity;

import android.view.View;
import butterknife.Unbinder;
import butterknife.internal.DebouncingOnClickListener;
import butterknife.internal.Finder;
import butterknife.internal.ViewBinder;
import com.karina.app.geopromociones.Login;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.Override;

public class LoginActivity$$ViewBinder<T extends Login.Activity.LoginActivity> implements ViewBinder<T> {
  @Override
  public Unbinder bind(final Finder finder, final T target, Object source) {
    InnerUnbinder unbinder = createUnbinder(target);
    View view;
    view = finder.findRequiredView(source, 2131492982, "field 'mNombreUsuario'");
    target.mNombreUsuario = finder.castView(view, 2131492982, "field 'mNombreUsuario'");
    view = finder.findRequiredView(source, 2131492984, "field 'mPasswordUsuario'");
    target.mPasswordUsuario = finder.castView(view, 2131492984, "field 'mPasswordUsuario'");
    view = finder.findRequiredView(source, 2131492985, "field 'mBotonIngresar' and method 'onClick'");
    target.mBotonIngresar = finder.castView(view, 2131492985, "field 'mBotonIngresar'");
    unbinder.view2131492985 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onClick(p0);
      }
    });
    view = finder.findRequiredView(source, 2131492986, "field 'mBotonRegistrar' and method 'onClick'");
    target.mBotonRegistrar = finder.castView(view, 2131492986, "field 'mBotonRegistrar'");
    unbinder.view2131492986 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onClick(p0);
      }
    });
    return unbinder;
  }

  protected InnerUnbinder<T> createUnbinder(T target) {
    return new InnerUnbinder(target);
  }

  protected static class InnerUnbinder<T extends Login.Activity.LoginActivity> implements Unbinder {
    private T target;

    View view2131492985;

    View view2131492986;

    protected InnerUnbinder(T target) {
      this.target = target;
    }

    @Override
    public final void unbind() {
      if (target == null) throw new IllegalStateException("Bindings already cleared.");
      unbind(target);
      target = null;
    }

    protected void unbind(T target) {
      target.mNombreUsuario = null;
      target.mPasswordUsuario = null;
      view2131492985.setOnClickListener(null);
      target.mBotonIngresar = null;
      view2131492986.setOnClickListener(null);
      target.mBotonRegistrar = null;
    }
  }
}
 ```

**Comment by JakeWharton** [comment] 2016-06-07 16:22
Dupe of #507 and already fixed on `master`. You can use 8.1.0-SNAPSHOT or just name your packages with lowercase per normal convention.

**Closed by JakeWharton** 2016-06-07 16:22 UTC

**Comment by grupobecm** [comment] 2016-06-07 16:26
Oh, sorry, i didnt see number #507, thanks!
