### ISSUE TITLE
 Different libraries report null pointers

### ISSUE THREAD

**Issue by wjianchen13** [JakeWharton/butterknife#1544] opened 2019-08-25 11:17 UTC
I have two Java files:
InheritedModel 1. java:

public class InheritedModel1 {
    @BindView(R2.id.tv_test1)
    protected TextView tvTest1;
    public InheritedModel1(Activity activity) {
        ButterKnife.bind(this, activity.getWindow().getDecorView());
    }
    public void initView(){
        tvTest1.setText("hello1");
    }
}

InheritedModel 1. java:

public class InheritedModel2 extends InheritedModel1{

    @BindView(R2.id.tv_test2)
    TextView tvTest2;

    public InheritedModel2(Activity activity) {
        super(activity);
        ButterKnife.bind(this, activity.getWindow().getDecorView());
    }

    public void initView(){
        tvTest1.setText("hello1");
        tvTest2.setText("hello2");
    }
}

If there is an inheritance relationship between the same module, such as Inherited Model 1 and Inherited Model 2, in a package at the same time, Inherited Model 2 generates the following files
  
@UiThread
  public InheritedModel2_ViewBinding(InheritedModel2 target, View source) {
        super(target, source);
        this.target = target;
        target.tvTest2 = Utils.findRequiredViewAsType(source, R.id.tv_test2, "field 'tvTest2'", 
  TextView.class);
  }

But in different libraries, such as Inherited Model 1 in Library A, Inherited Model 2 in Library B, the files generated by Inherited Model 2 are as follows:

  @UiThread
  public TestInheritedModel_ViewBinding(TestInheritedModel target, View source) {
    this.target = target;
    target.tvTest2 = Utils.findRequiredViewAsType(source, R.id.tv_test2, "field 'tvTest2'", TextView.class);
  }

This results in the use of Inherited Model 2 for different libraries and null pointers for variables of Inherited Model 1.

        model2 = new TestInheritedModel(this);
        model2.initView();

How to solve the problem that XXX_ViewBinding generated between different libraries does not generate super (target, source);

**Comment by JakeWharton** [comment] 2019-09-05 03:08
Dupe of #808. Recently fixed on master.

**Closed by JakeWharton** 2019-09-05 03:08 UTC
