### ISSUE TITLE
@BindFragment

### ISSUE THREAD

**Issue by medihack** [JakeWharton/butterknife#685] opened 2016-07-21 12:03 UTC
Wouldn't it be a nice to also reduce boilerplate by binding fragments?

```
mInfoPanelFragment = (InfoPanelFragment) getFragmentManager()
                .findFragmentById(R.id.info_panel_fragment);
```
to just
```
@BindFragment InfoPanelFragment mInfoPanelFragment;
```
Just an idea ;-)

**Comment by JakeWharton** [comment] 2016-07-21 14:00
Dupe of #15. Fragments are not UI so I don't see a reason to include them in this library.

**Closed by JakeWharton** 2016-07-21 14:00 UTC
