### ISSUE TITLE
Proposal: Butterknife extensions

### ISSUE THREAD

**Issue by JayNewstrom** [JakeWharton/butterknife#560] opened 2016-05-08 13:29 UTC
### High Level
Allow third party developers to add more functionality to butterknife by creating their own butterknife listener definitions.

This has multiple benefits:
- Butterknife could work for more than just first party Android views
- `ListenerClass` annotations are decoupled from this repo
- Third party libraries can add their own butterknife bindings packaged with their libraries

Butterknife extensions could be registered in a similar way to AutoValue Extensions. Then butterknife processor could generate the listener code.

**Comment by JakeWharton** [comment] 2016-05-09 15:24
I believe this is a dupe of #497. And for what it's worth, I've thought about this for a _long_ time, but just haven't been motivated to do that work.

**Closed by JakeWharton** 2016-05-09 15:24 UTC
