### ISSUE TITLE
 java.lang.IllegalArgumentException: couldn't make a guess for 

### ISSUE THREAD

**Issue by ximencx** [JakeWharton/butterknife#615] opened 2016-06-14 14:06 UTC
use this version,it have this problem
`Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: couldn't make a guess for cn.xm.xmvideoplayer.ui.activity.act_home`
when no use this,it not have this problem

**Comment by JakeWharton** [comment] 2016-06-14 14:07
This is fixed on `master` and will be in the next release, 8.1.0. You can use the 8.1.0-SNAPSHOT for now  if you like. Dupe of #507.

**Closed by JakeWharton** 2016-06-14 14:07 UTC

**Comment by ximencx** [comment] 2016-06-19 08:18
@JakeWharton thanks, I will try the release version.but I use the version 7.0.1 solove this problem.

**Comment by Malaika12Chohan** [comment] 2022-04-16 23:47
failed
:app:dataBindingGenBaseClassesDebug
couldn't make a guess for aligoldsmith.com.models.product
Cause: couldn't make a guess for aligoldsmith.com.models.product
i found that error no buddy can help me or guide me in good way
