### ISSUE TITLE
Error: Expected resource of type drawable [ResourceType]

### ISSUE THREAD

**Issue by ligi** [JakeWharton/butterknife#407] opened 2015-11-11 07:17 UTC
As Soon as I use com.neenbedankt.gradle.plugins:android-apt together with ButterKnife 7.0.1 and use the BindDrawable feature I get a problem with lint.:

```
/home/ligi/git/3rd/criticalmaps-android/app/build/generated/source/apt/release/de/stephanlindauer/criticalmaps/fragments/MapFragment$$ViewBinder.java:21: Error: Expected resource of type drawable [ResourceType]
    target.locationIcon = res.getDrawable(2130837593);
                                          ~~~~~~~~~~
/home/ligi/git/3rd/criticalmaps-android/app/build/generated/source/apt/release/de/stephanlindauer/criticalmaps/fragments/MapFragment$$ViewBinder.java:22: Error: Expected resource of type drawable [ResourceType]
    target.ownLocationIcon = res.getDrawable(2130837594);
                                             ~~~~~~~~~~


```

When I remove apt -> the lint error is gone

**Comment by JakeWharton** [comment] 2015-11-11 07:22
Dupe of #338. See last comment for a temporary workaround for now.

**Closed by JakeWharton** 2015-11-11 07:22 UTC
