### ISSUE TITLE
An Obsolete warning API " 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'." is shown  in Library At V10.1.0

### ISSUE THREAD

**Issue by EksDimension** [JakeWharton/butterknife#1431] opened 2019-01-16 06:33 UTC
I just follow the README.md like these

```
 dependencies {
   implementation 'com.jakewharton:butterknife:10.1.0'
   annotationProcessor 'com.jakewharton:butterknife-compiler:10.1.0'
 }
```
 

```
 buildscript {
   repositories {
     mavenCentral()
    }
   dependencies {
     classpath 'com.jakewharton:butterknife-gradle-plugin:10.1.0'
   }
 }
```

```
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
```

There is no problems when I use the low version buttknife(8.4) AndroidStudio(3.2) Gradle(3.2.0).
But now , a situation occurs that a weird Warning will be shown since I update Android-studio and Gradle.

Like this ↓↓↓↓↓↓
```
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
```
On my case ↓↓↓
1.AndroidStudio- Version 3.3.1
2.Gradle PlugIn version:3.3.1  and Gradle version:4.10.1-all.

It can work, it can be run and even Generated Into realeased APK. Everything is okay, but it's so bothering that it shows here every time . So what should I do to solve this problem?

**Comment by mrerhuo** [comment] 2019-01-16 13:22
ERROR: The Android Gradle plugin supports only Butterknife Gradle plugin version 9.0.0-rc2 and higher.
The following dependencies do not satisfy the required version:
root project 'WaveTest' -> com.jakewharton:butterknife-gradle-plugin:8.8.1
Affected Modules: app

**Comment by EksDimension** [comment] 2019-01-17 01:35
> ERROR: The Android Gradle plugin supports only Butterknife Gradle plugin version 9.0.0-rc2 and higher.
> The following dependencies do not satisfy the required version:
> root project 'WaveTest' -> com.jakewharton:butterknife-gradle-plugin:8.8.1
> Affected Modules: app
> 
> After I upgraded, I also prompted the above error.

Yeah, the new version of Gradle at 3.3 needs the new and updated ButterKnife that at lest 9.0.0.

However the new version Butterknife shows such a new Warning, it's so borthering . I have no idea for it...

**Comment by jasonpp** [comment] 2019-01-17 05:45
I got the same question with you guys. I follow Android Stduio's guild to setup the command in gradle.properties with android.debug.obsoleteApi = true and track the result like below:
`WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: It is currently called from the following trace:
java.lang.Thread.getStackTrace(Thread.java:1556)
com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:79)
com.android.build.gradle.internal.api.BaseVariantOutputImpl.getProcessResources(BaseVariantOutputImpl.java:86)
com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getProcessResources(null:-1)
butterknife.plugin.ButterKnifePlugin$configureR2Generation$1$1.execute(ButterKnifePlugin.kt:64)
butterknife.plugin.ButterKnifePlugin$configureR2Generation$1$1.execute(ButterKnifePlugin.kt:20)
org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
butterknife.plugin.ButterKnifePlugin$configureR2Generation$1.execute(ButterKnifePlugin.kt:63)
butterknife.plugin.ButterKnifePlugin$configureR2Generation$1.execute(ButterKnifePlugin.kt:20)`

**Comment by 957919019** [comment] 2019-01-24 05:33
the same error occur：

> ‘’API

 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.”

> 
with studio 3.3 and gradle 4.10.1

**Comment by Kingtous** [comment] 2019-02-02 14:58
I have the same question.
>ERROR: Android Gradle plugin 3.3.0 must not be applied to project 'D:\JianGuoYun\AndroidStudioProjects\WeatherReport\app' since version 3.3.0 was already applied to this project

I'm using AndroidStudio 3.3 and gradle version is 4.10.1

**Comment by Kingtous** [comment] 2019-02-02 15:01
I have the same problem and have no idea about that.

>ERROR: Android Gradle plugin 3.3.0 must not be applied to project since version 3.3.0 was already applied to this project

I'm using AndroidStudio 3.3 and gradle version is 4.10.1

**Comment by WilliamDaniel2406** [comment] 2019-02-06 04:47
anyone? I have the same error :(

**Comment by EksDimension** [comment] 2019-02-06 09:30
> anyone? I have the same error :(

Seems there is not solution for now
However luckly, it's only a warning, and it dosn't matter running, I will keep following the latest upgrade and hope it can be resolved one day.

**Comment by WilliamDaniel2406** [comment] 2019-02-07 14:35
> > anyone? I have the same error :(
> 
> Seems there is not solution for now
> However luckly, it's only a warning, and it dosn't matter running, I will keep following the latest upgrade and hope it can be resolved one day.

ohhh , thanks u

**Comment by wengqizun** [comment] 2019-02-11 07:28
Anybody know how to resolve this problem?Wait for next release?

**Comment by EksDimension** [comment] 2019-02-12 01:35
> Anybody know how to resolve this problem?Wait for next release?
Indeed, waiting for next butterknive version release.
Problem still exists ,although new patches of AndroidStudio for 3.3.1 and Gradle for 3.3.1 have been released.

**Comment by EksDimension** [comment] 2019-02-12 01:35
> Anybody know how to resolve this problem?Wait for next release?

Indeed, waiting for next butterknive version release.
Problem still exists ,although new patches of AndroidStudio for 3.3.1 and Gradle for 3.3.1 have been released.

**Comment by Payaml** [comment] 2019-02-13 06:52
This is because butterknife refers to the outdated API, and this warning occurs because Android Studio 3.3 updates the Gradle version. If you find this warning annoying, you can try to downgrade the Gradle version, currently only waiting for the butterknife update version and adapt The new version of Gradle syntax is the only solution

**Comment by EksDimension** [comment] 2019-02-13 07:05
> This is because butterknife refers to the outdated API, and this warning occurs because Android Studio 3.3 updates the Gradle version. If you find this warning annoying, you can try to downgrade the Gradle version, currently only waiting for the butterknife update version and adapt The new version of Gradle syntax is the only solution

That's what I thought, because I have checked all of my code ,and there was not any code refers to outdated API. There should be some code in Butterknife did it. 

I'll keep focusing on the new version of Butterknife~

**Comment by Payaml** [comment] 2019-02-15 01:51
> > This is because butterknife refers to the outdated API, and this warning occurs because Android Studio 3.3 updates the Gradle version. If you find this warning annoying, you can try to downgrade the Gradle version, currently only waiting for the butterknife update version and adapt The new version of Gradle syntax is the only solution
> 
> That's what I thought, because I have checked all of my code ,and there was not any code refers to outdated API. There should be some code in Butterknife did it.
> 
> I'll keep focusing on the new version of Butterknife~
Butterknife released a new version of 10.1.0, however it still does not solve the problem of obsolete APIs

**Comment by Payaml** [comment] 2019-02-15 01:52
> > This is because butterknife refers to the outdated API, and this warning occurs because Android Studio 3.3 updates the Gradle version. If you find this warning annoying, you can try to downgrade the Gradle version, currently only waiting for the butterknife update version and adapt The new version of Gradle syntax is the only solution
> 
> That's what I thought, because I have checked all of my code ,and there was not any code refers to outdated API. There should be some code in Butterknife did it.
> 
> I'll keep focusing on the new version of Butterknife~

Butterknife released a new version of 10.1.0, however it still does not solve the problem of obsolete APIs

**Comment by EksDimension** [comment] 2019-02-15 01:58
> > > This is because butterknife refers to the outdated API, and this warning occurs because Android Studio 3.3 updates the Gradle version. If you find this warning annoying, you can try to downgrade the Gradle version, currently only waiting for the butterknife update version and adapt The new version of Gradle syntax is the only solution
> > 
> > 
> > That's what I thought, because I have checked all of my code ,and there was not any code refers to outdated API. There should be some code in Butterknife did it.
> > I'll keep focusing on the new version of Butterknife~
> 
> Butterknife released a new version of 10.1.0, however it still does not solve the problem of obsolete APIs

Indeed, I've tried it just now, found it still occured~
So just let's keep focusing on the future version

**Comment by MatthewDevelop** [comment] 2019-03-05 09:06
Anyone has a solution?

**Comment by EksDimension** [comment] 2019-03-13 12:51
> Anyone has a solution?

Not yet, for now, just wait for the new version that solve it.

**Comment by emru67** [comment] 2019-03-21 09:05
Same problem...

**Comment by sjchmiela** [comment] 2019-03-21 12:22
Most probably it is caused by the following line:

https://github.com/JakeWharton/butterknife/blob/0cadabb00d82ada348c6e0350f5461944db89840/butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt#L64

`.processResources` is unwrapped to `.getProcessResources`.

A quick workaround for this issue would be to install `butterknife-gradle-plugin` straight from this pull request — https://github.com/JakeWharton/butterknife/pull/1478.

To do this, add `maven { url "https://jitpack.io" }` to your `buildscript.repositories` and then add the dependency for `butterknife-gradle-plugin` like this:

```groovy
classpath 'com.github.TWiStErRob.butterknife:butterknife-gradle-plugin:fix1431-SNAPSHOT'
```

Example:
```groovy
buildscript {
  repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://jitpack.io" }
    mavenCentral()
    google()
    jcenter()
  }
  dependencies {
    // https://github.com/JakeWharton/butterknife/pull/1478
    // https://jitpack.io/com/github/TWiStErRob/butterknife/fix1431-SNAPSHOT/build.log
    classpath 'com.github.TWiStErRob.butterknife:butterknife-gradle-plugin:fix1431-SNAPSHOT'
  }
}
```

**Comment by ymwm-lxl** [comment] 2019-03-27 06:15
AndroidX引用完成之后需要指定java的jdk版本。在build.gradle的app中添加如下：
`android {
     ......
    // 指定jdk版本
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}`

这种方法可以解决你的问题

**Comment by ymwm-lxl** [comment] 2019-03-27 06:36
我也出现了这个问题，在等待解决方案

**Comment by jijiaxin** [comment] 2019-04-03 07:35
mark

**Comment by zhaoyuehai** [comment] 2019-04-04 01:54
mark

**Comment by yanerchuang** [comment] 2019-04-12 07:51
+1

**Comment by githubhuwenpeng** [comment] 2019-04-12 08:04
没有强迫症，没事 只是一个警告不影响运行

**Comment by yangdepengyang** [comment] 2019-04-13 01:41
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
这个Android studio 配置文件
  classpath 'com.android.tools.build:gradle:3.3.2'
classpath 'com.jakewharton:butterknife-gradle-plugin:10.1.0'
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        mavenLocal()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
        maven { url 'https://jitpack.io' }
    }
}
//---------------
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip

**Comment by XIE87241203** [comment] 2019-04-17 08:27
mark

**Comment by sjchmiela** [comment] 2019-04-17 09:00
Hey all, just wanted to chime in that Github in the right sidebar of the issue there's a <kbd>Subscribe</kbd>/<kbd>Unsubscribe</kbd> button which you could use to subscribe to the issue without notifying all the subscribers that you're interested in this issue too. 🙂 Clicking the <kbd>Subscribe</kbd> button will have the same effect as commenting with _mark_ or _+1_.

<img width="288" alt="Zrzut ekranu 2019-04-17 o 10 56 58" src="https://user-images.githubusercontent.com/1151041/56274707-883ae980-60ff-11e9-9089-5f6abb0b3d7f.png">

To express interest in resolving the issue (the second purpose of commenting with _+1_) I would use Github's system of reactions.

<img width="863" alt="Zrzut ekranu 2019-04-17 o 10 59 54" src="https://user-images.githubusercontent.com/1151041/56274894-f1226180-60ff-11e9-8f4d-4afcdbf87e4b.png">

**Comment by joe-wojniak** [comment] 2019-06-15 16:28
@JakeWharton : Hi Jake, could you let us know what your plans are regarding this warning of an obsolete API?

**Comment by yangdepengyang** [comment] 2019-06-17 10:53
API 'variantOutput.getProcessResources()' 
 已过时请将 2019 年底替换为
'variantOutput.getProcessResourcesProvider()'.
猜测可能将于2019年底丢弃'variantOutput.getProcessResources()' 这个API接口

**Comment by nguyenlinhnttu** [comment] 2019-06-19 10:36
I use **Butterknife Library Plugin**, hope you update soon. @JakeWharton 
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: evchat

**Comment by xiangbo2015** [comment] 2019-07-20 15:54
我降低了gradle版本

![1563638033(1)](https://user-images.githubusercontent.com/15625116/61580904-c0602700-ab49-11e9-8d73-c65f54097283.jpg)

**Comment by lucers** [comment] 2019-08-25 03:56
How do I fix it?

**Comment by elliotching** [comment] 2019-08-25 05:13
You can only ignore it or lower down both version for built tools and butterknife plugin as screenshot above you

**Comment by felipecaldas** [comment] 2019-08-28 21:04
Having the same with 
implementation 'com.jakewharton:butterknife:10.1.0'
annotationProcessor 'com.jakewharton:butterknife-compiler:10.1.0'

Seems like this ticket has been going since February, maybe it has enough traction for an official fix?

**Comment by eziwen** [comment] 2019-09-04 07:36
等待解决方案

**Closed** 2019-09-08 20:01 UTC

**Comment by Chaitanyaha** [comment] 2019-09-20 11:52
I don't think think this issue is going to be solved 
most frustrating part is it shows up every time.... going on from January

**Comment by navidanchitrali** [comment] 2019-09-25 11:38
I have the same issue. Anybody here for help Please?

INFO: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

**Comment by p-fischer** [comment] 2019-09-25 11:47
This issue has been resolved and this issue thread has been closed. The latest release contains this fix. Try butterknife version `10.2.0`.

**Comment by krisez** [comment] 2019-11-12 01:32
build 3.4.0
gradle 5.1.1
classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-rc2'
bk-version 10.2.0
still warning
how to solve it?

**Comment by lucers** [comment] 2019-11-12 01:36
> build 3.4.0
> gradle 5.1.1
> classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-rc2'
> bk-version 10.2.0
> still warning
> how to solve it?

replace classpath version 9.0.0-rc2 to 10.2.0

**Comment by krisez** [comment] 2019-11-12 01:50
> > build 3.4.0
> > gradle 5.1.1
> > classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-rc2'
> > bk-version 10.2.0
> > still warning
> > how to solve it?
> 
> replace classpath version 9.0.0-rc2 to 10.2.0

Ok, but new wrong occured tha the 10.2.0 use androidx, but my project is support. and i dont plan to upgrade it to androidx
emmmm. what should i do

**Comment by KnIfER** [comment] 2021-12-21 11:33
how to use `getProcessResourcesProvider` then? ...
