### ISSUE TITLE
Feedback butterknife problem

### ISSUE THREAD

**Issue by TCQQ** [JakeWharton/butterknife#1087] opened 2017-09-23 14:37 UTC
How does butterknife support the "Preference" ?

**Comment by TCQQ** [comment] 2017-09-23 14:38
Like this view：
EditTextPreference etPref = (EditTextPreference) findPreference("edit_text_test");

**Comment by JakeWharton** [comment] 2017-09-23 16:42
Dupe of #209. No plans to do this.

**Closed by JakeWharton** 2017-09-23 16:42 UTC

**Comment by TCQQ** [comment] 2017-09-23 17:50
Cool, this is really a powerful library

**Comment by TCQQ** [comment] 2017-09-23 21:06
I try to add “@InjectPreference” or “@InjectView”, but they have error
![qq 20170924050510](https://user-images.githubusercontent.com/10644057/30777093-f9e70392-a0e5-11e7-9b4a-7e3059cecb67.png)
![qq 20170924050546](https://user-images.githubusercontent.com/10644057/30777099-0f79717c-a0e6-11e7-84f3-5348a68d465b.png)
