### ISSUE TITLE
R2 not work

### ISSUE THREAD

**Issue by Joy-Whale** [JakeWharton/butterknife#762] opened 2016-09-30 02:22 UTC
I used R2 in library module, but not work.The debugger ID is not equals with R2's ID

**Comment by Joy-Whale** [comment] 2016-09-30 02:55
here is my code:
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        //  lambda
        classpath 'me.tatarka:gradle-retrolambda:3.3.0-beta4'
        classpath 'me.tatarka.retrolambda.projectlombok:lombok.ast:0.2.3.a2'
        //  butterKnife
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }
    configurations.classpath.exclude group: 'com.android.tools.external.lombok'
}
```
library module:
```
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'

dependencies {
   compile 'com.jakewharton:butterknife:8.4.0'
   annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
}
```
and the java code:
```
@OnClick({R2.id.shop, R2.id.order})
	public void onClick(View view) {
		if(view.getId() == R.id.shop){
			startActivity(StoreGoodsDetailActivity.class);
		}else if(view.getId() == R.id.order){
			startActivity(StoreOrdersListActivity.class);
		}
	}
```

**Comment by gzncland** [comment] 2016-10-10 09:40
I got the same problem, somebody help us?

**Comment by Jungle68** [comment] 2016-10-11 06:33
I got the same problem, somebody help us?

**Comment by nukix** [comment] 2016-10-16 16:36
I got the same problem, somebody help us?

**Comment by JakeWharton** [comment] 2016-10-16 16:38
Provide a reproducible failure sample.

**Comment by nukix** [comment] 2016-10-16 17:01
@JakeWharton My project new an Android Library. And the library use ButterKnife. The app module dependencies the library. The app module use ButterKnife, but it not work.

**Comment by nukix** [comment] 2016-10-16 17:19
@JakeWharton like that https://github.com/nukix/Demo. My library module use ButterKnife. And my app module dependencies library module. But app module @BindView and @OnClick not work.

**Comment by chamnap** [comment] 2016-10-30 06:25
Doesn't work for me too.

**Comment by xxxzhi** [comment] 2016-10-31 01:51
@nukix you are not add 

```
apply plugin: 'android-apt'


dependencies {   
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
}
```

in your app module build.gradle. it means you didn't use butterknife apt in you app module. You just quoted ButterKnife. you should use apt to process butterknife anotation.

**Comment by Joy-Whale** [comment] 2016-10-31 01:55
@xxxzhi 
I used android gradle for version 2.2.+, so, I should not add an apt in my build.gradle!

**Comment by xxxzhi** [comment] 2016-10-31 02:51
@Joy-Whale I means if you want use butterknife in app module, you also should add 

`annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'` in your app module build.gradle even though you have added `annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'` in your library module build.gradle.

I base on this project https://github.com/nukix/Demo. I add  `annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'`  in app module build.gradle, then the Demo project run ok.



I am not very familiar with R2. 

@OnClick({R2.id.shop, R2.id.order})
    public void onClick(View view) {
        if(view.getId() == R.id.shop){
            startActivity(StoreGoodsDetailActivity.class);
        }else if(view.getId() == R.id.order){
            startActivity(StoreOrdersListActivity.class);
        }
    }

Why you don't use R2 in onClick method? I think It is possible R2.id.shop is not equal R.id.shop.

**Comment by aoldcat** [comment] 2016-11-17 01:12
@xxxzhi 为什么用了butterkinfe 8.4.0 gradle 2.2+每次需要clean项目注解的click方法才能起作用呢。

**Comment by xxxzhi** [comment] 2016-11-17 04:12
@aoldcat 我试了一下，倒是没这问题。你是用的android studio编译?我试了android studio编译跟命令行编译都没问题。

**Comment by domsu** [comment] 2017-02-01 13:06
Any news in this topic?

**Comment by shichaohui** [comment] 2017-03-15 13:47
I used R2 in library module, but not work. The R's ID is not equals with R2's ID.

**Comment by nukix** [comment] 2017-03-15 16:26
@JakeWharton The R's ID is not equals with R2's ID. And it led to the view is null. 
@xxxzhi 兄弟， 这个问题解决了吗?

**Comment by shichaohui** [comment] 2017-03-16 06:42
@JakeWharton 
I know the reason for the mistake, it looks like ButterKnife's Bug.
I have configured the Project and Library and Application according to the README.md.

Here is my code.

`BaseActivity` in Library as parent class:
```
public abstract class BaseActivity extends AppCompatActivity {

    @BindView(R2.id.tv_base)
    TextView tvBase;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        ViewGroup view  = (ViewGroup) getLayoutInflater().inflate(R.layout.activity_base, null);

        getLayoutInflater().inflate(getContentView(), view, true);

        setContentView(view);

        ButterKnife.bind(this);

        tvBase.setText("tvBase");
    }

    @LayoutRes
    protected abstract int getContentView();

}
```
`MainActivity` extends `BaseActivity` in Application:
```
public class MainActivity extends BaseActivity {

    @BindView(R.id.tv_main)
    TextView tvMain;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        tvMain.setText("main");
    }

    @Override
    protected int getContentView() {
        return R.layout.activity_main;
    }

}
```

Finally, I get an object for`tvMain` in `MainActivity`, but the `tvBase` in `BaseActivity` is null !
If `BaseActivity` isn't a parent class, everything is ok !
If `OtherActivity` in Library extends `BaseActivity`, everything is ok !

**Comment by JakeWharton** [comment] 2017-03-16 14:42
That's a dupe of #808 and since no one else has provided a complete failing sample I'm going to close this issue.

**Closed by JakeWharton** 2017-03-16 14:42 UTC

**Comment by richfuns** [comment] 2018-03-29 08:13
I am also got this problem too. I am also using R2 in my module. 

Version  Details below: 
classpath 'com.jakewharton:butterknife-gradle-plugin:8.5.0'
and
butterknife : "8.6.0",

    @OnClick({R2.id.ll_feedback, R2.id.ll_about_us, R2.id.stv})
    public void onClick(View v) {
        Log.e(TAG, "onClick: v id==" + v.getId());
        Log.e(TAG, "onClick:feedback_id:  "+ R2.id.ll_feedback);
        switch (v.getId()) {
            case R2.id.ll_feedback:
                Log.e(TAG, "onClick: feedback");
                break;
            case R2.id.ll_about_us:
                Log.e(TAG, "onClick: about_us");
                break;
            case R2.id.stv:
                Log.e(TAG, "onClick: stv ");
                break;
            default:
                Log.e(TAG, "No id matched");
                break;
        }
    }

**Comment by drybnikov** [comment] 2018-09-28 16:16
Why not create two onClick methods?

@OnClick({R2.id.shop})
    public void shopOnClick(View view) {}
@OnClick({R2.id.order})
    public void orderOnClick(View view) {}
