### ISSUE TITLE
IllegalStateException in sdk version 23

### ISSUE THREAD

**Issue by hhuimie** [JakeWharton/butterknife#402] opened 2015-11-05 05:54 UTC
i am running this project [ins](https://github.com/frogermcs/InstaMaterial/)
when i'm using default configuration as follow:
`'com.jakewharton:butterknife:6.1.0'`
`compileSdkVersion 22`
`buildToolsVersion "23.0.2"`
`targetSdkVersion 22`
that work **fine**!

**But** when i change the sdk version to `23` as follwo:
`compileSdkVersion 23`
`targetSdkVersion 23`
then i can not start the app, with a exception
`java.lang.IllegalStateException: Required view 'ivMenuUserProfilePhoto' with ID 2131558582 for field 'ivMenuUserProfilePhoto' was not found. If this view is optional add '@Optional' annotation.`

those activities cause the exception are:
[BaseActivity](https://github.com/frogermcs/InstaMaterial/blob/master/app/src/main/java/io/github/froger/instamaterial/ui/activity/BaseActivity.java)
[ BaseDrawerActivity](https://github.com/frogermcs/InstaMaterial/blob/master/app/src/main/java/io/github/froger/instamaterial/ui/activity/BaseDrawerActivity.java)
[MainActivity](https://github.com/frogermcs/InstaMaterial/blob/master/app/src/main/java/io/github/froger/instamaterial/ui/activity/MainActivity.java)

it seems no matter the version of butterknife
i had try to use version `7.1.0`
still useless
am i do something wrong??
thanks for helping!!

**Comment by isuPatches** [comment] 2015-11-05 13:22
If you are using a navigation view, I've seen that issue as well.  For a workaround I removed the header layout from the Navigation view and the bind calls and then in onCreate I used inflateHeaderView and found the views based off that:

```java
View headerLayout = mBaseDrawerActivityNavigationView.inflateHeaderView(R.layout.base_drawer_activity_left_drawer_header_layout);
mName = ButterKnife.findById(headerLayout, R.id.base_drawer_activity_left_drawer_name);
mProfileImage = ButterKnife.findById(headerLayout, R.id.base_drawer_activity_left_drawer_profile_image);
```

**Comment by JakeWharton** [comment] 2015-11-06 08:55
Yep, that view comes from the defined header view.

Dupe of #395. See the b.android.com link in that issue for more info.

**Closed by JakeWharton** 2015-11-06 08:55 UTC
