### ISSUE TITLE
All ID's generated in R2 are zeros

### ISSUE THREAD

**Issue by ernestp** [JakeWharton/butterknife#1578] opened 2020-01-09 03:17 UTC
// Generated code from Butter Knife gradle plugin. Do not modify!
package whatever;

import androidx.annotation.AnimRes;
import androidx.annotation.AttrRes;
import androidx.annotation.BoolRes;
import androidx.annotation.ColorRes;
import androidx.annotation.DimenRes;
import androidx.annotation.DrawableRes;
import androidx.annotation.IdRes;
import androidx.annotation.IntegerRes;
import androidx.annotation.LayoutRes;
import androidx.annotation.StringRes;
import androidx.annotation.StyleRes;
import androidx.annotation.StyleableRes;

public final class R2 {
  public static final class anim {
    @AnimRes
    public static final int abc_fade_in = 0x0;

    @AnimRes
    public static final int abc_fade_out = 0x0;

....

    implementation 'com.jakewharton:butterknife:10.2.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.0'

**Comment by JakeWharton** [comment] 2020-01-09 03:28
Dupe of #1549. Please upgrade to 10.2.1.

**Closed by JakeWharton** 2020-01-09 03:28 UTC

**Comment by ernestp** [comment] 2020-01-09 08:14
Happens on gradle 6 with 4.x gradle plugin. Reverted to 5, 3.5.3, no problem there.

**Comment by ernestp** [comment] 2020-02-26 09:16
Happens on gradle 5.6.4 with gradle plugin 3.6.0

**Comment by ernestp** [comment] 2020-02-26 09:17
On 10.2.1

**Comment by ernestp** [comment] 2020-02-26 09:28
False alarm, was using butterknife-gradle-plugin older version in project script
