### ISSUE TITLE
Package Upper-Case - not found symbol class

### ISSUE THREAD

**Issue by gennadijbgl** [JakeWharton/butterknife#594] opened 2016-05-26 08:12 UTC
When i move my fragments into package Fragments  - then i become error,
with stack help
http://stackoverflow.com/questions/36940575/cannot-find-symbol-class-on-butter-knife-generated-code
i renamed to fragments and there is no error

Error:(8, 38) error: cannot find symbol class Fragments
Error:(13, 63) error: package Fragments does not exist
Error:(27, 59) error: package Fragments does not exist

**Comment by JakeWharton** [comment] 2016-05-26 15:09
This is already fixed on master and will be in the next release. Dupe of #507.

Don't use uppercase package names for now.

**Closed by JakeWharton** 2016-05-26 15:09 UTC
