### ISSUE TITLE
Required bound views are null after calling ButterKnife.bind(this) in library module

### ISSUE THREAD

**Issue by Kolyall** [JakeWharton/butterknife#958] opened 2017-05-17 10:33 UTC
Here is example project [ButterKnifeModule](https://github.com/Kolyall/ButterKnifeModule)
I'm not using proguard
in app:
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
     }
}
dependencies {
    compile 'com.jakewharton:butterknife:8.6.0'
    apt  'com.jakewharton:butterknife-compiler:8.6.0'
}
```

```
package com.example;
@Layout(id = R.layout.activity_login)
public class MyActivity extends BaseActivity {
}
```
```
package com.example.activities;
public class BaseActivity extends BaseToolbarActivity {
}
```
in lib module:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.6.0'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'android-apt'
apply plugin: 'com.jakewharton.butterknife'
dependencies {
    compile 'com.jakewharton:butterknife:8.6.0'
    apt  'com.jakewharton:butterknife-compiler:8.6.0'
}
```
```
package com.base.ui.activities;
public class BaseToolbarActivity extends BaseContentActivity {
    @android.support.annotation.Nullable
    @butterknife.BindView(R2.id.toolbar)
    Toolbar mToolbar;
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);//setContentView and bind is called is super class BaseContentActivity 
         // mToolbar is NULL
      }
}

package com.base.ui.activities;
public class BaseContentActivity extends AppCompatActivity{
   
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
         Class cls = getClass();
        if (!cls.isAnnotationPresent(Layout.class)) return;
        Annotation annotation = cls.getAnnotation(Layout.class);
        Layout layout = (Layout) annotation;
        setContentView(layout.id());
        ButterKnife.bind(this);
       }
}
```
Log:
```
D/ButterKnife: Looking up binding for com.example.MyActivity 
D/ButterKnife: Not found. Trying superclass com.example.activities.BaseActivity
D/ButterKnife: Not found. Trying superclass com.base.ui.activities.BaseToolbarActivity
D/ButterKnife: HIT: Loaded binding class and constructor.
D/ButterKnife: Looking up binding for com.example.MyActivity 
D/ButterKnife: HIT: Cached in binding map.
```

**Comment by kschwall** [comment] 2017-07-05 17:15
I'm seeing this same issue.  Specifically, I have an abstract activity in a library module and the binding with ButterKnife 8.6.0 doesn't function for it at all; every bound view is null, onClicks are never called, etc.

Everything on my end is exactly the same as Kolyall here is seeing, except my debug log has a HIT:Loaded binding class and constructor for the second line.  There's no Not found errors at all.

**Comment by JakeWharton** [comment] 2017-07-18 05:24
Dupe of #808.

**Closed by JakeWharton** 2017-07-18 05:24 UTC
