### ISSUE TITLE
Every entry of R2 class has ID 0x0 with Android Plugin 3.6.0-alpha10 and Butterknife library plugin

### ISSUE THREAD

**Issue by NitroG42** [JakeWharton/butterknife#1549] opened 2019-09-06 13:05 UTC
Using 
```
classpath 'com.android.tools.build:gradle:3.6.0-alpha10'
classpath 'com.jakewharton:butterknife-gradle-plugin:10.1.0'
```
and

```
apply plugin: 'com.android.library'
apply plugin: 'com.jakewharton.butterknife'
```

Here is an extrac of the R2 class : 
```
public final class R2 {
  public static final class anim {
    @AnimRes
    public static final int abc_fade_in = 0x0;

    @AnimRes
    public static final int abc_fade_out = 0x0;

    @AnimRes
    public static final int abc_grow_fade_in_from_bottom = 0x0;

    @AnimRes
    public static final int abc_popup_enter = 0x0;

    @AnimRes
    public static final int abc_popup_exit = 0x0;

    @AnimRes
    public static final int abc_shrink_fade_out_from_bottom = 0x0;

    @AnimRes
    public static final int abc_slide_in_bottom = 0x0;

    @AnimRes
    public static final int abc_slide_in_top = 0x0;

    @AnimRes
    public static final int abc_slide_out_bottom = 0x0;

    @AnimRes
    public static final int abc_slide_out_top = 0x0;

    @AnimRes
    public static final int abc_tooltip_enter = 0x0;

    @AnimRes
    public static final int abc_tooltip_exit = 0x0;

    @AnimRes
    public static final int btn_checkbox_to_checked_box_inner_merged_animation = 0x0;

    @AnimRes
    public static final int btn_checkbox_to_checked_box_outer_merged_animation = 0x0;

    @AnimRes
    public static final int btn_checkbox_to_checked_icon_null_animation = 0x0;
```
Reproducible sample : https://github.com/NitroG42/Epoxy6Canary10Issue

If needed I can make an issue on Android Bug Tracker, I'm just not sure if it's a bug or a new behavior that requires some dev in the butterknife plugin.

**Comment by imorlowska** [comment] 2019-12-04 15:25
This is working as indented on the AGP side - does this break anything, Jake?

**Comment by athornz** [comment] 2019-12-17 21:53
With 3.6 now in RC a fix for this is pretty important.

**Comment by imorlowska** [comment] 2019-12-17 21:58
@athornz does this break anything? Does butterknife require the IDs to be unique? It is the expected behaviour in AGP.

**Comment by athornz** [comment] 2019-12-17 22:15
@imorlowska yes it's breaking any usages of the butterknife plugin since ids generated in the R2 class are all 0x0.

**Comment by imorlowska** [comment] 2019-12-17 22:20
You can temporarily go back to the previous behaviour by using android.useCompileClasspathLibraryRClasses=false (this will however get rid of the speed improvements that came with the compile classpath library r classes).

**Comment by athornz** [comment] 2019-12-17 22:23
ah, I didn't know about that one!

Would still be great to see a butterknife fix - is it still possible for butterknife to generate the R2 class as before?

**Comment by imorlowska** [comment] 2019-12-17 22:24
We'll see what we can do. :)

**Closed** 2019-12-18 19:42 UTC
Labels: bug

**Comment by wangpengwen** [comment] 2020-02-26 07:54
> You can temporarily go back to the previous behaviour by using android.useCompileClasspathLibraryRClasses=false (this will however get rid of the speed improvements that came with the compile classpath library r classes).

@imorlowska It helps~ I didn't know this option, either. Thank you~

**Comment by bingsenxie** [comment] 2020-04-11 14:48
> You can temporarily go back to the previous behaviour by using android.useCompileClasspathLibraryRClasses=false (this will however get rid of the speed improvements that came with the compile classpath library r classes).
How to set android.useCompileClasspathLibraryRClasses=false ?

**Comment by bingsenxie** [comment] 2020-04-11 14:55
> You can temporarily go back to the previous behaviour by using android.useCompileClasspathLibraryRClasses=false (this will however get rid of the speed improvements that came with the compile classpath library r classes).

ButterKnife 10.2.1 need AndroidX support. But my system cannot been updated to AndroidX now to avoid possible conflict. So try to 
set android.useCompileClasspathLibraryRClasses=false in gradle-wrapper.properties. But the problem still exits.
Which configuration file should been put to  android.useCompileClasspathLibraryRClasses=false
@imorlowska
