### ISSUE TITLE
Are butterknife annotations compatible with "feature" module concept?

### ISSUE THREAD

**Issue by preraktrivedi** [JakeWharton/butterknife#965] opened 2017-05-22 20:11 UTC
I'm migrating my app to support ["Instant Apps" ](https://developer.android.com/topic/instant-apps/index.html ) and refactored according to the required [project structure.](https://developer.android.com/topic/instant-apps/getting-started/structure.html)

I'm assuming that the feature modules are library projects and hence refactored my base module's `build.gradle` as follows:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.6.0'
    }
}

apply plugin: 'com.android.feature'
apply plugin: 'com.jakewharton.butterknife'

android {
    baseFeature true
    ....
}

```

However, I'm getting the following error:
```
Error:Unable to find method 'com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;'.
Possible causes for this unexpected error include:

- Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.). Re-download dependencies and sync project (requires network)

- The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem. Stop Gradle build processes (requires restart)

- Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

I'm narrowing it down to `butterknife` because before this library migration change, I was using the annotation processor dependency and was getting a bunch of the following compile time errors:
```
Error:(x, y) error: element value must be a constant expression
```

Hoping there's a workaround/upcoming fix to this. Looking forward to suggestions. Thanks guys!

**Comment by JakeWharton** [comment] 2017-05-22 20:16
Dupe of #963

**Closed by JakeWharton** 2017-05-22 20:16 UTC

**Comment by Quabynah** [comment] 2017-10-16 15:29
Same problem here too

**Comment by eliot29** [comment] 2017-10-27 08:45
Same problem here too, in a library, i am searching a way to fix since several hours :-/

**Comment by hookenwu** [comment] 2017-12-09 15:29
Same problem here, Still can't get a solution...
