### ISSUE TITLE
classpath com.jakewharton:butterknife-gradle-plugin

### ISSUE THREAD

**Issue by lyxxman** [JakeWharton/butterknife#1500] opened 2019-04-19 08:21 UTC
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: common

**Comment by JakeWharton** [comment] 2019-04-19 12:23
Dupe of #1431

**Closed by JakeWharton** 2019-04-19 12:23 UTC
