### ISSUE TITLE
Lib cant Find adapter class

### ISSUE THREAD

**Issue by Xopoko** [JakeWharton/butterknife#511] opened 2016-04-27 10:41 UTC
Error:(13, 98) error: package Adapters.FindTrackAdapter does not exist
![sdgfsdfgdgfs](https://cloud.githubusercontent.com/assets/6337061/14849827/e9f125a6-0c7d-11e6-83a7-7ef7b76d1dba.jpg)

**Comment by Xopoko** [comment] 2016-04-27 10:56
I refactor name of package "Adapters" to "adapters" and project compilled! 0~0

**Comment by JakeWharton** [comment] 2016-04-28 01:35
Yep. Dupe of #507. I'll fix soon.

**Closed by JakeWharton** 2016-04-28 01:35 UTC
