### ISSUE TITLE
apply plugin: 'com.jakewharton.butterknife' ,I get an error cuz this word;

### ISSUE THREAD

**Issue by luao419** [JakeWharton/butterknife#1165] opened 2017-12-19 17:59 UTC
![qq 20171220015558](https://user-images.githubusercontent.com/11911077/34171431-43b8b308-e529-11e7-8e8c-0db52a0f728e.png)
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        google()
        maven {
            url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'
        classpath "io.realm:realm-gradle-plugin:4.3.1"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

this is my build.gradle in my project;

**Comment by JakeWharton** [comment] 2017-12-19 18:10
Dupe of #1130. Use 9.0.0-SNAPSHOT for now.

**Closed by JakeWharton** 2017-12-19 18:10 UTC
