### ISSUE TITLE
Issue with encapsulation and inheritance(NullPointerException)

### ISSUE THREAD

**Issue by XieEDeHeiShou** [JakeWharton/butterknife#829] opened 2016-12-21 02:11 UTC
After read the introduction, I find that everytime I call `setContentView(int)` ,then I have to call `ButterKnife.bind(this)` to let it work.
So I decide to write an abstract class to do that automatically like this:
> public abstract class MyActivity extends AppCompatActivity{
>     public void onCreate(Bunlde){
>         setContentView( setContentViewImp( ) );
>         ButterKnife.bind(this);                             
>     }
>     protected abstract int setContentViewImp( );
>     public void onContentChanged(){
>         initView();
>     }
>     protected abstract void initView();
> }

Then I write another class `A`, which inherit `MyActivity` and implement those abstract methods, `A` works as expected.
While I write class `B`, do the same what I did to `A`, I get a `NullPointerException` at the frist line in `initView()`.

I tried to use inflater to reload `setContentView(View)` and use 'bind(this,view)' to solve this problem,failed.
I noticed that fragment need `unbinder.unbind()`,so I tried this in `MyActivity`, hope it works ... Well.it doesn't.
Finally,I write `ButterKnife.bind(this)` manually at the first line in `initView()` in `B`,it works...

Is there a compatibility problem with encapsulation and inheritance?

**Comment by JakeWharton** [comment] 2017-02-24 14:48
Dupe of #808

**Closed by JakeWharton** 2017-02-24 14:48 UTC
