### ISSUE TITLE
WARNING: API 'variantOutput.getProcessResources()

### ISSUE THREAD

**Issue by 568571931** [JakeWharton/butterknife#1548] opened 2019-09-03 01:39 UTC
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'

**Comment by JakeWharton** [comment] 2019-09-03 01:52
Dupe of #1431

**Closed by JakeWharton** 2019-09-03 01:52 UTC
