### ISSUE TITLE
Can't work when Gradle plugin upgrade to 3.1.2

### ISSUE THREAD

**Issue by wangxuefang** [JakeWharton/butterknife#1282] opened 2018-05-25 03:09 UTC
`    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2' // add plugin
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'  //添加这一行

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }`

Issuse:
`Error:Unable to find method 'com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.`

**Comment by JakeWharton** [comment] 2018-05-25 03:12
Dupe of #1200. You have to use 9.0.0-SNAPSHOT for now. Repository link is in the README in the download section.

**Closed by JakeWharton** 2018-05-25 03:12 UTC
