### ISSUE TITLE
java.lang.NullPointerException due to library

### ISSUE THREAD

**Issue by wuxuan2811** [JakeWharton/butterknife#1543] opened 2019-08-15 03:41 UTC
I have use ButterKnife in library and create BaseActivity
public abstract class BaseActivity {
    /**
     * 返回
     */
    @BindView(R2.id.text)
    TextView mLibraryTxt;
...
@Override
  public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        ButterKnife.bind(this);
    }

 public void setTitle(String content){
   mLibraryTxt.setText(content);
 }
}

Then I create TestActivity in app module which use the library
public class TestActvity extends BaseActivity{
@BindView(R.id.mainTextId)
    TextView mMainTxt;
...
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        setTitle("Test");
        mMainTxt.setText("change");
    }
}
when I use 'mBackImg', it show "Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference"

**Comment by wuxuan2811** [comment] 2019-08-15 03:44
I have a discription error , change 'mBackImg'  to 'mLibraryTxt'

**Comment by JakeWharton** [comment] 2019-09-05 03:09
Dupe of #808. Recently fixed on master for next release.

**Closed by JakeWharton** 2019-09-05 03:09 UTC
