### ISSUE TITLE
@OnProgressChanged listener binding?

### ISSUE THREAD

**Issue by jonstavis** [JakeWharton/butterknife#564] opened 2016-05-10 12:57 UTC
Hi, is there any way to leverage Butterknife for a SeekBar?

I am looking for an `@OnProgressChanged` listener annotation and don't see one in the API.

Thanks!

**Comment by JakeWharton** [comment] 2016-05-10 14:16
Dupe of #441.

**Closed by JakeWharton** 2016-05-10 14:16 UTC
