### ISSUE TITLE
R2 file generation failed

### ISSUE THREAD

**Issue by TAGASK** [JakeWharton/butterknife#1451] opened 2019-02-04 09:56 UTC
:instant-app-features:home:generateAlphaDebugFeatureR2

this task is failing for an instant app feature module.

Why ? because the R.txt file is not generate for feature module instant app
but only for the base feature.

Screenshots: 
baseFeature 
<img width="320" alt="screen shot 2019-01-17 at 5 53 36 pm" src="https://user-images.githubusercontent.com/10398568/52200818-2cdcb780-2883-11e9-9bd0-02c767ab2d41.png">

Feature
<img width="324" alt="screen shot 2019-01-17 at 5 53 47 pm" src="https://user-images.githubusercontent.com/10398568/52200837-382fe300-2883-11e9-9ac6-0b7a25411af7.png">

this is the error I m facing :
java.io.FileNotFoundException: /android_app/instant-app-features/home/build/intermediates/symbols/feature/alpha/debug/R.txt (No such file or directory).

sample project (instant app with multiple feature) to reproduce :
https://github.com/googlesamples/android-instant-apps/tree/master/hello-feature-module

**Comment by JakeWharton** [comment] 2019-02-04 16:39
Dupe of #1441.

**Closed by JakeWharton** 2019-02-04 16:39 UTC
