### ISSUE TITLE
gradle exception in library module, gradle need to be update

### ISSUE THREAD

**Issue by zjhuang0** [JakeWharton/butterknife#940] opened 2017-05-02 03:08 UTC
Error:Could not find com.android.tools.build:gradle:2.2.0.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
Required by:
    project :sdk > com.jakewharton:butterknife-gradle-plugin:8.5.1

**Comment by JakeWharton** [comment] 2017-05-02 03:18
Dupe of #936.

**Closed by JakeWharton** 2017-05-02 03:18 UTC
