### ISSUE TITLE
NonConstantResourceId warning in Android Studio 4.1

### ISSUE THREAD

**Issue by hormesiel** [JakeWharton/butterknife#1636] opened 2020-10-19 09:30 UTC
After a recent update to AS 4.1 and Android Gradle Plugin v4.0.2 the following warning started to appear on every ButterKnife annotation that receives an id :

![image](https://user-images.githubusercontent.com/1585006/96426811-077e1180-11fe-11eb-932e-e0a904bbbebf.png)

Is it safe to disable this inspection rule or is there a risk that projects using ButterKnife will break when the Android Gradle Plugin v5 is released?

**Comment by JakeWharton** [comment] 2020-10-19 13:17
Dupe of #1634 and #1635. Either migrate to using R2 or to solutions that don't rely on annotations such as view binding.

**Closed as completed by JakeWharton** 2020-10-19 13:17 UTC
