### ISSUE TITLE
Injecting into superclass when only subclass is modified.

### ISSUE THREAD

**Issue by lhunath** [JakeWharton/butterknife#440] opened 2016-02-09 19:19 UTC
Given a class hierarchy like so:

`class A { @Bind(R.id.a) View viewA; { ButterKnife.inject(this) } }`

`class B extends A { @Bind(R.id.b) View viewB; }`

Where A and B exist in their own file, `A.java` and `B.java`, when you modify `B.java` without modifying `A.java`, you end up with `viewA` being `null` at runtime.

I use the following ANT build script to ensure all classes that include `@Bind` annotations are included for each build.  This is not ideal but avoids the issue.

```
<project basedir=".">
    <description>
        Fix ButterKnife bug caused by the compiler not including unmodified @Bind classes.
    </description>

    <target name="prebuild" description="Ensure the right source files are added to the build">
        <touch>
            <fileset dir="../source/java">
                <contains text="@Bind" />
            </fileset>
        </touch>
    </target>
</project>
```

I'm not sure if a bug exists for this issue already; but it's likely related to #362

**Comment by tasomaniac** [comment] 2016-02-11 13:08
I am just curious. When you do a clean build, does it work or is it always null?

**Comment by lhunath** [comment] 2016-02-11 13:32
Works just fine from a clean build.  The issue only happens when the build is done using only the subclass.

Modifying both the subclass and the superclass files also doesn't trigger this bug.

**Comment by Tinkling** [comment] 2016-02-11 13:48
https://github.com/JakeWharton/butterknife/issues/438

**Comment by JakeWharton** [comment] 2016-04-23 07:10
This is a dupe of #31. Maybe we can write out superclass details into a non-Java file to be read across invocations?

**Closed by JakeWharton** 2016-04-23 07:10 UTC
