### ISSUE TITLE
Superclass Injection in another module returns null

### ISSUE THREAD

**Issue by kshirsagarps** [JakeWharton/butterknife#1157] opened 2017-11-28 23:00 UTC
I have two custom views Foo and Bar, where Bar extends Foo.
Foo and Bar both are in different modules.
Foo looks like this:

```
public class Foo extends LinearLayout {

    @BindView(R2.id.foo_container) protected LinearLayout fooContainer;
    ...

    @Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        inflate(getContext(), getLayoutId(), this);
        ButterKnife.bind(this);
    }

    @LayoutRes
    protected int getLayoutId() {
        return R.layout.foo_selector;
    }
    ...
}
```

If I call ```@BindView``` in Bar, ButterKnife binds the view inside Bar but not the view in the superclass Foo.
And thus the ```fooContainer``` in Foo is always null.
Bar looks like this:

```
public class Bar extends Foo {

    @BindView(R.id.scroll_view) HorizontalScrollView scrollView;
    ...

    @LayoutRes
    @Override
    protected int getLayoutId() {
        return R.layout.bar_selector;
    }
    ...
}
```

However, works fine for ```findViewById(R.id.scroll_view))``` in Bar, instead of calling ```@BindView```.  BTW I am using BK version 8.5.1.
Any idea what may be the problem?

**Comment by JakeWharton** [comment] 2017-11-28 23:22
Dupe of #808. This isn't supported currently.

**Closed by JakeWharton** 2017-11-28 23:22 UTC
