### ISSUE TITLE
ButterKnife-reflect crashes when used in a module

### ISSUE THREAD

**Issue by Alonexx** [JakeWharton/butterknife#1509] opened 2019-05-05 15:43 UTC
Different from butterknife-compiler, which generates _ViewBinding.java calling R.id directly, butterknife-reflect uses constants in R2.

On my multiple module project, constants in R2 may be merged with other modules that causes constants change.

Any idea about this?

**Comment by JakeWharton** [comment] 2019-05-05 15:46
Dupe of #1449. I don't expect this to ever work.

**Closed by JakeWharton** 2019-05-05 15:46 UTC

**Comment by Alonexx** [comment] 2019-05-11 16:18
However, for people who has a really large project, which generates hundreds of _ViewBinding.java in multiple modules, it's impossible to get benefits from butterknife-reflect.

**Comment by JakeWharton** [comment] 2019-05-11 17:22
Yep. You'll want to migrate to view binding which was announced at I/O and will be part of the 3.6 release of Android Studio
