### ISSUE TITLE
Cannot resolve symbol error in ViewBinder

### ISSUE THREAD

**Issue by DMcP89** [JakeWharton/butterknife#515] opened 2016-04-28 01:26 UTC
I am getting a cannot resolve symbol error when trying to build my app. The error is coming from the ViewBinder class that Butterknife generates.

C:\Users\dave\AndroidStudioProjects\SoundBoard\app\build\generated\source\apt\debug\com\wochstudios\InfiniteSoundboards\MainActivity$$ViewBinder.java:8: error: cannot find symbol
import com.wochstudios.InfiniteSoundboards;
                      ^
  symbol:   class InfiniteSoundboards
  location: package [com.wochstudios]

I have attached the activity where I am using ButterKnife. I have all the dependencies setup in my gradle files and I've tried cleaning and rebuilding the app a few times now. Not sure why this issue is coming up. 

[MainActivity.txt](https://github.com/JakeWharton/butterknife/files/239626/MainActivity.txt)

**Comment by JakeWharton** [comment] 2016-04-28 01:34
It's because your package name is uppercase. Dupe of #507. I'll fix soon.

**Closed by JakeWharton** 2016-04-28 01:34 UTC

**Comment by DMcP89** [comment] 2016-04-28 01:49
thanks!

**Comment by Kiran89kumar** [comment] 2016-05-05 14:19
Thanks u saved my time

**Comment by CesarLogan18** [comment] 2016-06-04 15:32
Thank you JakeWharton , works perfectly.
