### ISSUE TITLE
@Nullable + @OnClick is weak

### ISSUE THREAD

**Issue by swankjesse** [JakeWharton/butterknife#437] opened 2016-02-02 05:33 UTC
I’ve got a button that’s present in the tablet layout but absent from the phone layout. Unfortunately, ButterKnife needs `@Nullable` on the `@OnClick` binding for this button:

```
  @OnClick({ R.id.toolbarEditPlayersText }) @Nullable
  void clickEditPlayersText() {
    clickEditPlayers();
  }
```

Seems like `@Nullable` is a lousy name for the binding to be optional.

**Comment by JakeWharton** [comment] 2016-02-02 05:41
Dupe of #306. Already fixed on `master` for the next release.

**Comment by JakeWharton** [comment] 2016-02-02 05:42
Been slacking, will get back to it someday...

**Closed by JakeWharton** 2016-02-02 05:41 UTC
