### ISSUE TITLE
ObsoleteLintCustomCheck warning

### ISSUE THREAD

**Issue by iovorobiev** [JakeWharton/butterknife#1079] opened 2017-09-13 06:07 UTC
Getting this warning during lint analysis with butterknife version 8.8.1:

`Lint found one or more custom checks using its older Java API; these checks are still run in compatibility mode, but this causes duplicated parsing, and in the next version lint will no longer include this legacy mode. Make sure the following lint detectors are upgraded to the new API: butterknife.lint.InvalidR2UsageDetector
`

**Comment by JakeWharton** [comment] 2017-09-13 13:49
Dupe of #1074.

**Closed by JakeWharton** 2017-09-13 13:49 UTC
