### ISSUE TITLE
how to use butterknife in a library module?

### ISSUE THREAD

**Issue by yummyChina** [JakeWharton/butterknife#1008] opened 2017-07-13 05:51 UTC
Now, I have put my baseactivity in a serparated module,and I inject the butterknife in the baseactivity,Then I would implements the baseactivity in my app module, The problem is that it throw NullPointerException  on widgets which defined by butterknife,anyone can help me?

**Comment by JakeWharton** [comment] 2017-07-13 13:19
This configuration is not supported. Dupe of #808.

**Closed by JakeWharton** 2017-07-13 13:19 UTC

**Comment by dinukapj** [comment] 2017-11-08 04:52
Hi @JakeWharton any updates on this yet? May I ask what's the issue that's blocking this configuration? Thanks.
