### ISSUE TITLE
Can't set TabLayout titles in FragmentPageAdapter using @BindString

### ISSUE THREAD

**Issue by Nxt3** [JakeWharton/butterknife#447] opened 2016-02-24 19:49 UTC
This code will leave the titles blank.

```
public class RecentReleasesFragmentPagerAdapter extends FragmentPagerAdapter {

    @BindString(R.string.recent_movies_title) CharSequence recentMovies;
    @BindString(R.string.recent_dvds_title) CharSequence recentDVDs;

    final int PAGE_COUNT = 2;
    private Context context;

    public RecentReleasesFragmentPagerAdapter(FragmentManager fm, Context context) {
        super(fm);
        this.context = context;
    }

    @Override
    public int getCount() {
        return PAGE_COUNT;
    }

    @Override
    public Fragment getItem(int position) {
        return RecentReleasesFragment.newInstance(position + 1);
    }

    @Override
    public CharSequence getPageTitle(int position) {
        switch (position) {
            case 0:
                return recentMovies;
                //THIS WORKS: return context.getResources().getString(R.string.recent_movies_title);
            case 1:
                return recentDVDs;
                //THIS WORKS: return context.getResources().getString(R.string.recent_dvds_title);
        }
        return super.getPageTitle(position);
    }
}
```

Excuse my ignorance, but I'm unsure of any reason why Butterknife doesn't work here.

**Comment by JakeWharton** [comment] 2016-02-24 19:56
You never called `ButterKnife.bind` to run the generated code. But since this doing view binding, it doesn't make much sense since you have no root view to pass in which makes this a dupe of #282.

**Closed by JakeWharton** 2016-02-24 19:56 UTC

**Comment by Nxt3** [comment] 2016-02-24 21:00
Screw me. Sorry for wasting your time.
