### ISSUE TITLE
9.0.0-rc1 is incompatible with Jetifier 1.0.0-beta02

### ISSUE THREAD

**Issue by gildor** [JakeWharton/butterknife#1397] opened 2018-10-31 08:05 UTC
If you try to use jetifier 1.0.0-beta02 (to fix [the issue with compatibility with Dagger 2.17+](https://issuetracker.google.com/issues/115738511)) build will fail with this error:

```Caused by: java.lang.RuntimeException: Failed to transform '/Users/gildor/.gradle/caches/modules-2/files-2.1/com.jakewharton/butterknife-compiler/9.0.0-rc1/e66446c78b80f3e91fad9d222942aa3b7d26355/butterknife-compiler-9.0.0-rc1.jar' using Jetifier. Reason: The given artifact contains a string literal with a package reference 'android.support.v4.content' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file.```

Looks that jetifier checks that jar doesn't use reflections for `android.support.v4` and finds this string in ButterKnife. I reported this issue to corresponding issue on Android issue tracker, but maybe something can be done also on side of butterknife

**Comment by JakeWharton** [comment] 2018-10-31 13:32
Dupe of #1395

**Closed by JakeWharton** 2018-10-31 13:32 UTC
