### ISSUE TITLE
butterknife:8.1.0  java.lang.NullPointerException

### ISSUE THREAD

**Issue by alphater** [JakeWharton/butterknife#649] opened 2016-06-27 04:22 UTC
`  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.anony.iphoto/com.anony.iphoto.ui.found.FoundActivity}: java.lang.NullPointerException
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2596)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2653)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:156)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:157)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5872)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.NullPointerException
                                                                           at com.anony.iphoto.ui.found.FoundFragment.showMessageLayout(FoundFragment.java:173)
                                                                           at com.anony.iphoto.corecommon.ui.found.FoundPresenter.getIPhotos(FoundPresenter.java:38)
                                                                           at com.anony.iphoto.ui.found.FoundFragment.onCreateView(FoundFragment.java:90)`

**code**
`   @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_found, container, false);
        ButterKnife.bind(this, rootView);
}`
`    @BindView(R.id.recycler_view2)
    RecyclerView mRecyclerView;`
`        <android.support.v4.widget.SwipeRefreshLayout
            android:id="@+id/swipere_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recycler_view2"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_gravity="center_horizontal|top"
                android:padding="@dimen/content_recycler_view_padding"
                tools:listitem="@layout/item_found"/>
        </android.support.v4.widget.SwipeRefreshLayout>`

**project build.gradle**
`buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "http://mvn.leancloud.cn/nexus/content/repositories/releases" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'me.tatarka:gradle-retrolambda:3.3.0-beta3'
    }
}`
**mobile build.gradle**
`apply plugin: 'com.neenbedankt.android-apt`
`dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    final DAGGER_VERSION = '2.2'
    def daggerCompiler = "com.google.dagger:dagger-compiler:$DAGGER_VERSION"
    apt daggerCompiler

    compile project(':CoreCommon')

    compile 'com.jakewharton:butterknife:8.1.0'
    apt 'com.jakewharton:butterknife-compiler:8.1.0'
}`

**Comment by JakeWharton** [comment] 2016-06-27 04:44
What's inside `FoundFragment`? Do you see the code being generated at `build/generated/source/apt/`?

**Comment by alphater** [comment] 2016-06-27 05:24
`import com.anony.iphoto.corecommon.ui.found.FoundPresenter;
import dagger.MembersInjector;
import javax.annotation.Generated;
import javax.inject.Provider;

@Generated(
  value = "dagger.internal.codegen.ComponentProcessor",
  comments = "https://google.github.io/dagger"
)
public final class FoundFragment_MembersInjector implements MembersInjector<FoundFragment> {
  private final Provider<FoundAdapter> mAdapterProvider;

  private final Provider<FoundPresenter> mFoundPresenterProvider;

  public FoundFragment_MembersInjector(
      Provider<FoundAdapter> mAdapterProvider, Provider<FoundPresenter> mFoundPresenterProvider) {
    assert mAdapterProvider != null;
    this.mAdapterProvider = mAdapterProvider;
    assert mFoundPresenterProvider != null;
    this.mFoundPresenterProvider = mFoundPresenterProvider;
  }

  public static MembersInjector<FoundFragment> create(
      Provider<FoundAdapter> mAdapterProvider, Provider<FoundPresenter> mFoundPresenterProvider) {
    return new FoundFragment_MembersInjector(mAdapterProvider, mFoundPresenterProvider);
  }

  @Override
  public void injectMembers(FoundFragment instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.mAdapter = mAdapterProvider.get();
    instance.mFoundPresenter = mFoundPresenterProvider.get();
  }

  public static void injectMAdapter(
      FoundFragment instance, Provider<FoundAdapter> mAdapterProvider) {
    instance.mAdapter = mAdapterProvider.get();
  }

  public static void injectMFoundPresenter(
      FoundFragment instance, Provider<FoundPresenter> mFoundPresenterProvider) {
    instance.mFoundPresenter = mFoundPresenterProvider.get();
  }
}`
**The above is the edited code**

**Comment by JakeWharton** [comment] 2016-06-27 05:25
That's generated code by Dagger, not Butter Knife.

**Comment by JakeWharton** [comment] 2016-06-27 05:26
If you're not seeing classes like "Foo$$ViewBinder" then Butter Knife isn't configured correctly in your build.

**Comment by alphater** [comment] 2016-06-27 05:26
`    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_found, container, false);
        ButterKnife.bind(this, rootView);
        mFoundPresenter.attachView(this);
        isStart = true;
        ((AppCompatActivity) getActivity()).setSupportActionBar(mToolbar);
        mAdapter.setContext2(getActivity());

        setupViews();
        mFoundPresenter.getIPhotos(mAdapter.getItemCount(), false);
        return rootView;
    }`
`    
    @BindView(R.id.recycler_view2)
    RecyclerView mRecyclerView;
    @BindView(R.id.swipere_layout)
    SwipeRefreshLayout mSwipereLayout;`
**Above for the FoundFragment code**

**Comment by alphater** [comment] 2016-06-27 05:29
Yes, no production, but my code configuration did not find the problem

**Comment by alphater** [comment] 2016-06-27 05:35
The new version (8.1.0) was the problem, the old version (7-) normal compiler

**Comment by JakeWharton** [comment] 2016-06-27 05:36
There nothing wrong with 8.1.0, the problem is with your build. If you can
isolate the problem into a reproducible example I can take a look.
Otherwise I can't really speculate as to what's wrong without seeing the
project.

**Comment by alphater** [comment] 2016-06-27 05:38
Let me try, thank you.

**Comment by alphater** [comment] 2016-06-28 01:06
Have solved the problem. The reason for this is because I have a dependence on the library, butterknife configuration only in the library were, not in the mobile configuration, so always NullPointerException and in mobile configuration, you can normally run.

**Comment by hzsweers** [comment] 2016-07-04 00:25
Safe to close this then?

**Closed** 2016-07-10 20:56 UTC
